scenario:
  name: one_obstacle
  num_episodes: 1001
  baseline_frequency: 50
  max_time: 150
  time_step: 0.25
  domain: 100
  trial_num: 24
learning_agent:
  type: DQN
  max_action: 0.261799,1500
  gamma: 0.9
  drop_out: 0.0
  nodes_in_layer: 100
  optimizer: adam
  learn_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  #optimizer: rms_prop
  #learn_rate: 0.0005
  #alpha: 0.99
  #momentum: 0
  memory_capacity: 100000
  epsilon_start: 0.9
  epsilon_end: 0.2
  epsilon_decay: 1500
  update_target: 10
  n_batches: 10
  batch_size: 2048
  loss: huber
  tau: 0.05
replay_data:
  capacity: 1000
  replay_strategy: proximity
  proximity_threshold: 10.0
  close_fraction: 0.3
  far_fraction: 0.7
boat:
  type: utility
  sensor: lidar
  mode: propeller_and_power
reward:
  crash: -100.0
  success: 100.0
  distance_norm: 1.0
  prox_crash: 0.1
  fuel_use: 10.0
  angle: 0.075