scenario:
  name: no_obstacles
  num_episodes: 5001
  baseline_frequency: 20
  max_time: 150
  time_step: 0.25
  domain: 100
learning_agent:
  type: DQN
  max_action: 0.261799,1500
  gamma: 0.9
  drop_out: 0.0
  nodes_in_layer: 100
  optimizer: adam
  learn_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999
  #optimizer: rms_prop
  #learn_rate: 0.0005
  #alpha: 0.99
  #momentum: 0
  memory_capacity: 100000
  epsilon_start: 0.9
  epsilon_end: 0.2
  epsilon_decay: 1500
  update_target: 10
  n_batches: 100
  batch_size: 2048
  loss: huber
  memory_split: 0.6
  tau: 0.05
boat:
  type: sail_boat
  sensor: lidar
  mode: propeller_and_power
reward:
  crash: -100.0
  success: 100.0
  distance_norm: 1.0
  prox_crash: 0.1
  fuel_use: 10.0
  angle: 0.075